# Generated by Django 3.2.3 on 2024-08-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_short_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='short_id',
            new_name='short_id_url',
        ),
    ]
