# Generated by Django 3.2.3 on 2024-08-19 12:05

import django.core.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное поле.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Разрешены только буквы, цифры и символы @/./+/-/_.', regex='^[\\w.@+-]+\\Z'), recipes.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
